# Generated by Django 3.1.5 on 2021-02-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_card', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('comments', models.CharField(max_length=100)),
                ('attach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach', to='Auth.attach')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ManyToManyField(to='Auth.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sum', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_time', models.DateTimeField()),
                ('in_this_month', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagesForAttached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedUnit', models.CharField(default=0, max_length=50)),
                ('distanseUnit', models.CharField(default=0, max_length=50)),
                ('fuelConsumption', models.CharField(default=0, max_length=50)),
                ('volume', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SingleRecomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTransport', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('yearOfMade', models.CharField(max_length=4)),
                ('yearOfPurchase', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=30)),
                ('numberOfTank', models.IntegerField(default=0)),
                ('firstTankType', models.CharField(max_length=30)),
                ('firstTankVolume', models.IntegerField(default=0)),
                ('secondTankType', models.CharField(blank=True, max_length=30, null=True)),
                ('secondTankVolume', models.IntegerField(blank=True, default=0, null=True)),
                ('run', models.IntegerField(default=0)),
                ('averageRun', models.IntegerField(default=0)),
                ('techPassport', models.CharField(max_length=30)),
                ('cards_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_user', to='Auth.cards')),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailOrPhone', models.CharField(max_length=200, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Auth.transportdetail')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='Auth.selectedunits')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleRecomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendations', models.ManyToManyField(to='Auth.SingleRecomendation')),
            ],
        ),
        migrations.CreateModel(
            name='MarkaRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_marka', models.CharField(default=0, max_length=50)),
                ('model', models.ManyToManyField(to='Auth.ModelRegister')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Auth.expenses'),
        ),
        migrations.AddField(
            model_name='card',
            name='expense',
            field=models.ManyToManyField(to='Auth.Expense'),
        ),
        migrations.AddField(
            model_name='attach',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='Auth.ImagesForAttached'),
        ),
        migrations.CreateModel(
            name='AbovePartRecomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Auth.markaregister')),
            ],
        ),
    ]
