# Generated by Django 3.1.5 on 2021-01-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAutoRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1)),
                ('marka', models.CharField(choices=[('Marka', models.CharField(max_length=1)), ('Model', 'B')], max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedUnit', models.CharField(default=0, max_length=50)),
                ('distanseUnit', models.CharField(default=0, max_length=50)),
                ('fuelConsumption', models.CharField(default=0, max_length=50)),
                ('volume', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTransport', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('yearOfMade', models.CharField(max_length=4)),
                ('yearOfPurchase', models.CharField(max_length=4)),
                ('firstTank', models.BooleanField(default=True)),
                ('kilometerPetrol', models.IntegerField(default=0)),
                ('numberPetrol', models.IntegerField(default=0)),
                ('secondTank', models.BooleanField(default=True)),
                ('kilometerGas', models.IntegerField(default=0)),
                ('numberGas', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailOrPhone', models.CharField(max_length=200, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Auth.transportdetail')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='Auth.selectedunits')),
            ],
        ),
    ]
