# Generated by Django 3.1.5 on 2021-02-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abovepartrecomendation',
            name='image',
            field=models.ImageField(upload_to='admin/'),
        ),
    ]
