# Generated by Django 3.1.5 on 2021-01-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationautoregister',
            name='marka',
            field=models.CharField(choices=[('Marka', models.CharField(default=0, max_length=100)), ('Model', 'B')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='informationautoregister',
            name='text',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
