# Generated by Django 3.1.5 on 2021-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20210201_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelregister',
            name='recomendations',
            field=models.ManyToManyField(to='Auth.SingleRecomendation'),
        ),
        migrations.AddField(
            model_name='singlerecomendation',
            name='recomended_probeg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attach',
            name='image',
            field=models.ManyToManyField(to='Auth.ImagesForAttached'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='all_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='in_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='markaregister',
            name='name_of_marka',
            field=models.CharField(default=0, max_length=50, verbose_name='название марки'),
        ),
        migrations.DeleteModel(
            name='MultipleRecomendation',
        ),
    ]
