# Generated by Django 3.1.7 on 2021-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20210617_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type_cards',
            field=models.ManyToManyField(to='Auth.RecommendCards', verbose_name='Для каких карточек'),
        ),
    ]
