# Generated by Django 3.1.4 on 2020-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20201217_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='emailOrPhone',
            field=models.CharField(default=0, max_length=254, unique=True, verbose_name='email or phone'),
            preserve_default=False,
        ),
    ]
