# Generated by Django 3.1.5 on 2021-02-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20210201_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='RecommendedChange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach', to='Auth.recommendedchange'),
        ),
    ]
