# Generated by Django 3.1.5 on 2021-01-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20210121_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markaregister',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='Auth.modelregister'),
        ),
    ]
