# Generated by Django 3.1.4 on 2020-12-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20201219_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTransport', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('yearOfMade', models.CharField(max_length=4)),
                ('yearOfPurchase', models.CharField(max_length=4)),
                ('firstTank', models.BooleanField(default=True)),
                ('kilometerPetrol', models.IntegerField(default=0)),
                ('numberPetrol', models.IntegerField(default=0)),
                ('secondTank', models.BooleanField(default=True)),
                ('kilometerGas', models.IntegerField(default=0)),
                ('numberGas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailOrPhone', models.CharField(max_length=200, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Auth.transportdetail')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
