# Generated by Django 3.1.5 on 2021-02-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_card_recommendedchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markaregister',
            name='name_of_marka',
            field=models.CharField(default=0, max_length=50, verbose_name='Название марки'),
        ),
        migrations.AlterField(
            model_name='modelregister',
            name='name_of_model',
            field=models.CharField(max_length=50, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='modelregister',
            name='recomendations',
            field=models.ManyToManyField(to='Auth.SingleRecomendation', verbose_name='Рекомендации для модели'),
        ),
        migrations.AlterField(
            model_name='singlerecomendation',
            name='description',
            field=models.TextField(verbose_name='Описание рекомендации'),
        ),
        migrations.AlterField(
            model_name='singlerecomendation',
            name='main_name',
            field=models.CharField(max_length=70, verbose_name='Название для рекомендации'),
        ),
        migrations.AlterField(
            model_name='singlerecomendation',
            name='recomended_probeg',
            field=models.IntegerField(default=0, verbose_name='Рекомендованный пробег'),
        ),
    ]
