# Generated by Django 3.1.4 on 2020-12-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20201219_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedUnit', models.CharField(default=0, max_length=50)),
                ('distanseUnit', models.CharField(default=0, max_length=50)),
                ('fuelConsumption', models.CharField(default=0, max_length=50)),
                ('volume', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertransport',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='Auth.selectedunits'),
        ),
    ]
