# Generated by Django 3.1.5 on 2021-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20210121_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markaregister',
            name='model',
        ),
        migrations.AddField(
            model_name='markaregister',
            name='model',
            field=models.ManyToManyField(to='Auth.ModelRegister'),
        ),
    ]
