# Generated by Django 3.1.7 on 2021-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20210809_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelregister',
            name='text_above',
            field=models.TextField(default=1, verbose_name='Описание модели(Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendcards',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название карточки(Русский)'),
        ),
    ]
