# Generated by Django 3.1.5 on 2021-01-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20210121_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markaregister',
            name='model',
        ),
        migrations.AddField(
            model_name='markaregister',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.modelregister'),
        ),
    ]
