# Generated by Django 3.1.5 on 2021-02-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20210201_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='abovepartrecomendation',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Auth.modelregister'),
        ),
    ]
