# Generated by Django 3.1.7 on 2021-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20210809_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountproaccount',
            name='name_subscribe',
            field=models.CharField(max_length=50, verbose_name='Название подписки(Русский)'),
        ),
        migrations.AlterField(
            model_name='amountproaccount',
            name='name_subscribe_eng',
            field=models.CharField(max_length=50, verbose_name='Название подписки(Английский)'),
        ),
        migrations.AlterField(
            model_name='amountproaccount',
            name='name_subscribe_uzb',
            field=models.CharField(max_length=50, verbose_name='Название подписки(Узбекский)'),
        ),
    ]
