# Generated by Django 3.1.5 on 2021-02-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_abovepartrecomendation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelregister',
            name='image_above',
            field=models.ImageField(default=1, upload_to='admin/', verbose_name='Фото для модели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelregister',
            name='text_above',
            field=models.TextField(default=1, verbose_name='Описание модели'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AbovePartRecomendation',
        ),
    ]
