# Generated by Django 3.1.7 on 2021-08-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20210809_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountproaccount',
            old_name='name_subscribe',
            new_name='name_subscribe_ru',
        ),
        migrations.RenameField(
            model_name='modelregister',
            old_name='text_above',
            new_name='text_above_ru',
        ),
        migrations.RenameField(
            model_name='singlerecomendation',
            old_name='main_name',
            new_name='main_name_ru',
        ),
    ]
