# Generated by Django 3.1.5 on 2021-02-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20210202_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='RecommendedChange',
            new_name='change',
        ),
        migrations.AlterField(
            model_name='singlerecomendation',
            name='recomended_probeg',
            field=models.FloatField(default=0, verbose_name='Рекомендованный пробег в километрах'),
        ),
    ]
