# Generated by Django 3.1.7 on 2021-08-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20210809_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelregister',
            old_name='text_above_ru',
            new_name='text_above',
        ),
    ]
