# Generated by Django 3.1.5 on 2021-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_auto_20210121_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportdetail',
            old_name='kilometerGas',
            new_name='firstTankVolume',
        ),
        migrations.RenameField(
            model_name='transportdetail',
            old_name='kilometerPetrol',
            new_name='numberOfTank',
        ),
        migrations.RenameField(
            model_name='transportdetail',
            old_name='numberGas',
            new_name='secondTankVolume',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='firstTank',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='numberPetrol',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='secondTank',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='volume',
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='firstTankType',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='secondTankType',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
