# Generated by Django 3.1.7 on 2021-08-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_auto_20210809_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type_car',
        ),
    ]
