# Generated by Django 3.1.5 on 2021-01-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_auto_20210123_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='secondTankType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='secondTankVolume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
