# Generated by Django 3.1.5 on 2021-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_auto_20210202_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='initial_run',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='run',
            field=models.FloatField(default=0),
        ),
    ]
