# Generated by Django 3.1.5 on 2021-01-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_auto_20210123_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransport',
            name='cards',
        ),
        migrations.AddField(
            model_name='usertransport',
            name='cards',
            field=models.ManyToManyField(to='Auth.TransportDetail'),
        ),
    ]
