# Generated by Django 3.1.5 on 2021-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_auto_20210123_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
