# Generated by Django 3.1.5 on 2021-02-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin/adds/', verbose_name='Реклама')),
                ('links', models.CharField(max_length=200, verbose_name='Линк для перехода')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('state', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('phoneOrMail', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycom_transaction_id', models.CharField(max_length=25)),
                ('paycom_time', models.CharField(max_length=13)),
                ('paycom_time_datetime', models.DateField()),
                ('create_time', models.DateField()),
                ('perform_time', models.DateField()),
                ('cancel_time', models.DateField()),
                ('amount', models.IntegerField()),
                ('state', models.IntegerField()),
                ('reason', models.IntegerField()),
                ('receivers', models.CharField(max_length=500)),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.usertransport'),
        ),
        migrations.AddField(
            model_name='usertransport',
            name='last_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertransport',
            name='pro_account',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='usertransport',
            name='cards',
        ),
        migrations.AddField(
            model_name='usertransport',
            name='cards',
            field=models.ManyToManyField(to='Auth.TransportDetail'),
        ),
    ]
