# Generated by Django 3.1.4 on 2021-03-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_auto_20210220_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adds',
            options={'verbose_name_plural': 'Реклама'},
        ),
        migrations.AlterModelOptions(
            name='markaregister',
            options={'verbose_name_plural': 'Марка'},
        ),
        migrations.AlterModelOptions(
            name='modelregister',
            options={'verbose_name_plural': 'Модель'},
        ),
        migrations.AlterModelOptions(
            name='singlerecomendation',
            options={'verbose_name_plural': 'Рекоммендации'},
        ),
        migrations.AlterModelOptions(
            name='usertransport',
            options={'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AddField(
            model_name='card',
            name='date_of_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='storeCard',
            field=models.ManyToManyField(related_name='store_card', to='Auth.Card'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card',
            field=models.ManyToManyField(related_name='card', to='Auth.Card'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
