# Generated by Django 3.1.4 on 2021-04-04 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0020_auto_20210403_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymepropayment',
            name='duration',
        ),
        migrations.AddField(
            model_name='usertransport',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymepropayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payme', to='Auth.usertransport'),
        ),
        migrations.CreateModel(
            name='PaynetProPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_paynet', to='Auth.usertransport')),
            ],
        ),
    ]
