# Generated by Django 3.1.4 on 2021-04-05 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0021_auto_20210404_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('paid_time', models.DateField()),
                ('transactionId', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usertransport',
            name='balans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paynetpropayment',
            name='customerId',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='paynetpropayment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='client_paynet', to='Auth.usertransport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paynetpropayment',
            name='check_get',
            field=models.ManyToManyField(to='Auth.Transaction'),
        ),
    ]
