# Generated by Django 3.1.4 on 2021-04-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0022_auto_20210405_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paynetpropayment',
            name='check_get',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Auth.paynetpropayment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
