# Generated by Django 3.1.4 on 2021-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0023_auto_20210407_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Название карточки')),
                ('recommend_run', models.IntegerField(default=0, verbose_name='Рекоммендованный пробег в километрах')),
            ],
            options={
                'verbose_name_plural': 'Рекоммендованые карточки',
            },
        ),
        migrations.AddField(
            model_name='modelregister',
            name='recommend_card',
            field=models.ManyToManyField(to='Auth.RecommendCards', verbose_name='Рекомендованные карточки'),
        ),
    ]
