# Generated by Django 3.1.7 on 2021-05-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0024_auto_20210410_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.ManyToManyField(to='Auth.Expense')),
                ('image', models.ManyToManyField(to='Auth.ImagesForAttached')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_for_images', to='Auth.usertransport')),
            ],
        ),
    ]
