# Generated by Django 3.1.7 on 2021-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markaregister',
            name='name_of_marka',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='Название марки'),
        ),
    ]
