# Generated by Django 3.2.3 on 2021-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_auto_20210519_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransport',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, to='Auth.TransportDetail'),
        ),
    ]
