# Generated by Django 3.2.3 on 2021-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0027_alter_usertransport_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Заглавние')),
                ('body', models.CharField(max_length=50, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Пуш сообщения для все пользователей',
            },
        ),
    ]
