# Generated by Django 3.1.7 on 2021-06-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0028_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Push уведомления'},
        ),
    ]
