# Generated by Django 3.2.3 on 2021-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0030_auto_20210608_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='marka',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
