# Generated by Django 3.2.3 on 2021-06-09 07:59

import Auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0031_auto_20210608_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='providerTrnId',
            field=models.BigIntegerField(default=Auth.utils.create_new_ref_number, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expense',
            field=models.ManyToManyField(blank=True, null=True, to='Auth.Expense'),
        ),
        migrations.AlterField(
            model_name='recommendcards',
            name='recommend_run',
            field=models.FloatField(default=0, verbose_name='Рекоммендованный пробег в километрах'),
        ),
    ]
