# Generated by Django 3.2.3 on 2021-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0032_auto_20210609_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
    ]
