# Generated by Django 3.2.3 on 2021-06-09 10:52

import Auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0033_auto_20210609_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymepropayment',
            name='id',
            field=models.IntegerField(default=Auth.utils.create_new_ref_number, primary_key=True, serialize=False, unique=True),
        ),
    ]
