# Generated by Django 3.2.3 on 2021-06-09 11:57

import Auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0034_alter_paymepropayment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymepropayment',
            name='hashed_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymepropayment',
            name='id',
            field=models.BigIntegerField(default=Auth.utils.create_new_ref_number, primary_key=True, serialize=False, unique=True),
        ),
    ]
