# Generated by Django 3.2.3 on 2021-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0035_auto_20210609_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymepropayment',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
