# Generated by Django 3.2.3 on 2021-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0036_alter_paymepropayment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountproaccount',
            name='type',
            field=models.IntegerField(choices=[('Одноразовая', 1), ('Подписка', 2)], default=1),
        ),
    ]
