# Generated by Django 3.2.3 on 2021-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0037_amountproaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountproaccount',
            name='type',
            field=models.IntegerField(choices=[(1, 'Одноразовая'), (2, 'Подписка')], default=1),
        ),
    ]
