# Generated by Django 3.2.3 on 2021-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0039_alter_amountproaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountproaccount',
            name='type',
            field=models.IntegerField(choices=[(0, 'Одноразовая оплата'), (1, 'Подписка')], default=0, verbose_name='Тип подписки'),
        ),
    ]
