# Generated by Django 3.2.3 on 2021-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0040_alter_amountproaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymepropayment',
            name='hashed_id',
            field=models.CharField(max_length=50),
        ),
    ]
