# Generated by Django 3.2.3 on 2021-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0041_alter_paymepropayment_hashed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedunits',
            name='distanseUnit',
            field=models.CharField(default='км', max_length=5),
        ),
        migrations.AlterField(
            model_name='selectedunits',
            name='fuelConsumption',
            field=models.CharField(default='км/л', max_length=5),
        ),
        migrations.AlterField(
            model_name='selectedunits',
            name='speedUnit',
            field=models.CharField(default='км/д', max_length=5),
        ),
        migrations.AlterField(
            model_name='selectedunits',
            name='volume',
            field=models.CharField(default='UZS', max_length=5),
        ),
    ]
