# Generated by Django 3.2.3 on 2021-06-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0045_auto_20210615_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='run_type',
            field=models.IntegerField(choices=[(0, 'Все'), (0, 'пробег в километрах 0 - 100000'), (1, 'пробег в километрах 100000 - 200000'), (2, 'пробег в километрах 200000 и больше')], default=0, verbose_name='Пробег машины'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_car',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Механика'), (2, 'Автомат')], default=0, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_cards',
            field=models.ManyToManyField(to='Auth.Card', verbose_name='Для каких карточек'),
        ),
        migrations.AlterField(
            model_name='recommendcards',
            name='type_car',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Механика'), (2, 'Автомат')]),
        ),
    ]
