# Generated by Django 3.2.3 on 2021-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0046_auto_20210615_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='run_type',
        ),
        migrations.AlterField(
            model_name='recommendedchange',
            name='initial_run',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedchange',
            name='run',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedchange',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
