# Generated by Django 3.2.3 on 2021-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0047_auto_20210615_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='type_car',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Механика'), (2, 'Автомат')], default=1),
        ),
    ]
